spring:
  application:
    name: gateway
    config:
      import: "configserver:"
    cloud:
      config:
        discovery:
          service-id: config-server
          enabled: true
        fail-fast: true
        retry:
          max-use-random-policy: true
        max-interval: 6000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
server:
  port: 8080