spring:
  application:
    name: analyzer
    config:
      import: 'configserver:'
    cloud:
      config:
        discovery:
          service-id: config-server
          enabled: true
        fail-fast: true
        retry:
          initial-interval: 2000
          max-attempts: 6
          max-interval: 6000
eureka:
  instance:
    hostname: localhost
    metadata-map:
      supported-hub-event-avro: v1
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8081